require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ThingItemsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ThingItem. As you add validations to ThingItem, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ThingItemsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all thing_items as @thing_items" do
      thing_item = ThingItem.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:thing_items)).to eq([thing_item])
    end
  end

  describe "GET show" do
    it "assigns the requested thing_item as @thing_item" do
      thing_item = ThingItem.create! valid_attributes
      get :show, {:id => thing_item.to_param}, valid_session
      expect(assigns(:thing_item)).to eq(thing_item)
    end
  end

  describe "GET new" do
    it "assigns a new thing_item as @thing_item" do
      get :new, {}, valid_session
      expect(assigns(:thing_item)).to be_a_new(ThingItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested thing_item as @thing_item" do
      thing_item = ThingItem.create! valid_attributes
      get :edit, {:id => thing_item.to_param}, valid_session
      expect(assigns(:thing_item)).to eq(thing_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ThingItem" do
        expect {
          post :create, {:thing_item => valid_attributes}, valid_session
        }.to change(ThingItem, :count).by(1)
      end

      it "assigns a newly created thing_item as @thing_item" do
        post :create, {:thing_item => valid_attributes}, valid_session
        expect(assigns(:thing_item)).to be_a(ThingItem)
        expect(assigns(:thing_item)).to be_persisted
      end

      it "redirects to the created thing_item" do
        post :create, {:thing_item => valid_attributes}, valid_session
        expect(response).to redirect_to(ThingItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved thing_item as @thing_item" do
        post :create, {:thing_item => invalid_attributes}, valid_session
        expect(assigns(:thing_item)).to be_a_new(ThingItem)
      end

      it "re-renders the 'new' template" do
        post :create, {:thing_item => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested thing_item" do
        thing_item = ThingItem.create! valid_attributes
        put :update, {:id => thing_item.to_param, :thing_item => new_attributes}, valid_session
        thing_item.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested thing_item as @thing_item" do
        thing_item = ThingItem.create! valid_attributes
        put :update, {:id => thing_item.to_param, :thing_item => valid_attributes}, valid_session
        expect(assigns(:thing_item)).to eq(thing_item)
      end

      it "redirects to the thing_item" do
        thing_item = ThingItem.create! valid_attributes
        put :update, {:id => thing_item.to_param, :thing_item => valid_attributes}, valid_session
        expect(response).to redirect_to(thing_item)
      end
    end

    describe "with invalid params" do
      it "assigns the thing_item as @thing_item" do
        thing_item = ThingItem.create! valid_attributes
        put :update, {:id => thing_item.to_param, :thing_item => invalid_attributes}, valid_session
        expect(assigns(:thing_item)).to eq(thing_item)
      end

      it "re-renders the 'edit' template" do
        thing_item = ThingItem.create! valid_attributes
        put :update, {:id => thing_item.to_param, :thing_item => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested thing_item" do
      thing_item = ThingItem.create! valid_attributes
      expect {
        delete :destroy, {:id => thing_item.to_param}, valid_session
      }.to change(ThingItem, :count).by(-1)
    end

    it "redirects to the thing_items list" do
      thing_item = ThingItem.create! valid_attributes
      delete :destroy, {:id => thing_item.to_param}, valid_session
      expect(response).to redirect_to(thing_items_url)
    end
  end

end
